apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-wiremock-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-wiremock
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-wiremock
    spec:
      containers:
        - name: {{ .Release.Name }}-wiremock-container
          image: holomekc/wiremock-gui:3.2.0.0
          args:
            - --enable-browser-proxying
          volumeMounts:
            - name: mappings
              mountPath: /home/wiremock/mappings
            - name: files
              mountPath: /home/wiremock/__files
          resources:
            limits:
              cpu: "0.5"
              memory: 512Mi
            requests:
              cpu: "0.1"
              memory: 256Mi
      volumes:
        - name: mappings
          configMap:
            name: {{ .Release.Name }}-wiremock-mappings
        - name: files
          configMap:
            name: {{ .Release.Name }}-wiremock-files
