apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-wiremock-service
spec:
  selector:
    app: {{ .Release.Name }}-wiremock
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
